# These are the lists the user picks from in the user interface (drop lists).
# If the user does not find what they want, they can still paste their own web address.
# Every address below was tested with readFeed on 3 October 2026. Some outlets change their feed address
# from time to time. A feed that stops working is skipped by the loops with a clear message,
# so one dead address never stops a briefing. tests/live_checks.py tests the whole list again.

NEWS_OUTLETS = {
    "World": {
        "BBC World": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "BBC Top Stories": "https://feeds.bbci.co.uk/news/rss.xml",
        "NPR News": "https://feeds.npr.org/1001/rss.xml",
        "Al Jazeera English": "https://www.aljazeera.com/xml/rss/all.xml",
        "The Guardian World": "https://www.theguardian.com/world/rss",
        "New York Times World": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        "Washington Post World": "https://feeds.washingtonpost.com/rss/world",
        "Sky News World": "https://feeds.skynews.com/feeds/rss/world.xml",
        "DW English": "https://rss.dw.com/rdf/rss-en-all",
        "France 24 English": "https://www.france24.com/en/rss",
        "Euronews": "https://www.euronews.com/rss?format=mrss",
        "UN News": "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        "CBS News World": "https://www.cbsnews.com/latest/rss/world",
        "ABC News International": "https://abcnews.go.com/abcnews/internationalheadlines",
        "NBC News": "https://feeds.nbcnews.com/nbcnews/public/news",
        "Fox News World": "https://moxie.foxnews.com/google-publisher/world.xml",
        "The Independent World": "https://www.independent.co.uk/news/world/rss",
        "The Diplomat": "https://thediplomat.com/feed/",
        "Foreign Policy": "https://foreignpolicy.com/feed/",
        "Global Voices": "https://globalvoices.org/feed/",
    },
    "United States": {
        "New York Times Home": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
        "Los Angeles Times": "https://www.latimes.com/world-nation/rss2.0.xml",
        "PBS NewsHour": "https://www.pbs.org/newshour/feeds/rss/headlines",
        "The Hill": "https://thehill.com/news/feed/",
        "Axios": "https://api.axios.com/feed/",
        "Washington Post Politics": "https://feeds.washingtonpost.com/rss/politics",
        "NBC News US": "https://feeds.nbcnews.com/nbcnews/public/us-news",
        "CBS News US": "https://www.cbsnews.com/latest/rss/us",
        "Fox News": "https://moxie.foxnews.com/google-publisher/latest.xml",
        "Politico Politics": "https://rss.politico.com/politics-news.xml",
    },
    "United Kingdom": {
        "BBC UK": "https://feeds.bbci.co.uk/news/uk/rss.xml",
        "The Guardian UK": "https://www.theguardian.com/uk/rss",
        "Sky News UK": "https://feeds.skynews.com/feeds/rss/uk.xml",
        "The Independent": "https://www.independent.co.uk/news/uk/rss",
        "Daily Mail": "https://www.dailymail.co.uk/news/index.rss",
        "Metro": "https://metro.co.uk/feed/",
    },
    "Europe": {
        "DW Deutsch": "https://rss.dw.com/rdf/rss-de-all",
        "Der Spiegel": "https://www.spiegel.de/schlagzeilen/index.rss",
        "Tagesschau": "https://www.tagesschau.de/index~rss2.xml",
        "Le Monde": "https://www.lemonde.fr/rss/une.xml",
        "France 24 Francais": "https://www.france24.com/fr/rss",
        "El Pais": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "ANSA English": "https://www.ansa.it/english/news/english_nr_rss.xml",
        "RTE Ireland": "https://www.rte.ie/feeds/rss/?index=/news/",
        "Kyiv Independent": "https://kyivindependent.com/news-archive/rss/",
        "The Local Germany": "https://feeds.thelocal.com/rss/de",
        "Meduza": "https://meduza.io/rss/en/all",
    },
    "Middle East": {
        "Middle East Eye": "https://www.middleeasteye.net/rss",
        "Haaretz": "https://www.haaretz.com/srv/haaretz-latest-headlines",
        "The National UAE": "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml",
        "Daily Sabah": "https://www.dailysabah.com/rssFeed/10",
        "Al-Monitor": "https://www.al-monitor.com/rss",
        "Egypt Independent": "https://www.egyptindependent.com/feed/",
        "Tehran Times": "https://www.tehrantimes.com/rss",
        "Anadolu Agency": "https://www.aa.com.tr/en/rss/default?cat=world",
        "Asharq Al-Awsat English": "https://english.aawsat.com/feed",
    },
    "Arabic": {
        "BBC Arabic": "https://feeds.bbci.co.uk/arabic/rss.xml",
        "Al Jazeera Arabic": "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9",
        "France 24 Arabic": "https://www.france24.com/ar/rss",
        "DW Arabic": "https://rss.dw.com/rdf/rss-ar-all",
        "Sky News Arabia": "https://www.skynewsarabia.com/web/rss",
        "Asharq Al-Awsat": "https://aawsat.com/feed",
        "Al Quds Al Arabi": "https://www.alquds.co.uk/feed/",
        "Anadolu Arabic": "https://www.aa.com.tr/ar/rss/default?cat=guncel",
        "Euronews Arabic": "https://arabic.euronews.com/rss?format=mrss",
        "CNN Arabic": "https://arabic.cnn.com/rss",
    },
    "Asia and Pacific": {
        "South China Morning Post": "https://www.scmp.com/rss/91/feed",
        "Japan Times": "https://www.japantimes.co.jp/feed/",
        "The Straits Times": "https://www.straitstimes.com/news/world/rss.xml",
        "Times of India": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
        "The Hindu": "https://www.thehindu.com/news/feeder/default.rss",
        "NDTV": "https://feeds.feedburner.com/ndtvnews-top-stories",
        "Hindustan Times": "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
        "Korea Herald": "http://www.koreaherald.com/common/rss_xml.php?ct=102",
        "Channel News Asia": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
        "ABC News Australia": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "Sydney Morning Herald": "https://www.smh.com.au/rss/feed.xml",
        "NZ Herald": "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/nz/?outputType=xml",
        "RNZ": "https://www.rnz.co.nz/rss/news.xml",
        "Taipei Times": "https://www.taipeitimes.com/xml/index.rss",
        "The Guardian Australia": "https://www.theguardian.com/australia-news/rss",
        "Bangkok Post": "https://www.bangkokpost.com/rss/data/topstories.xml",
        "Philippine Daily Inquirer": "https://newsinfo.inquirer.net/feed",
        "Nikkei Asia": "https://asia.nikkei.com/rss/feed/nar",
        "The Korea Times": "https://www.koreatimes.co.kr/www/rss/world.xml",
        "Mainichi": "https://mainichi.jp/english/rss/etc/mainichi-flash.rss",
        "Vietnam News": "https://vietnamnews.vn/rss/society.rss",
        "Rappler": "https://www.rappler.com/feed/",
    },
    "Africa": {
        "BBC Africa": "https://feeds.bbci.co.uk/news/world/africa/rss.xml",
        "allAfrica": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
        "Premium Times Nigeria": "https://www.premiumtimesng.com/feed",
        "Africanews": "https://www.africanews.com/feed/rss",
        "The Guardian Africa": "https://www.theguardian.com/world/africa/rss",
        "Daily Nation Kenya": "https://nation.africa/kenya/rss.xml",
        "The East African": "https://www.theeastafrican.co.ke/rss.xml",
        "Punch Nigeria": "https://punchng.com/feed/",
        "Vanguard Nigeria": "https://www.vanguardngr.com/feed/",
        "The Citizen Tanzania": "https://www.thecitizen.co.tz/rss.xml",
        "Ethiopia Insight": "https://www.ethiopia-insight.com/feed/",
        "The Africa Report": "https://www.theafricareport.com/feed/",
        "IOL South Africa": "https://iol.co.za/rss/",
    },
    "Americas": {
        "CBC News": "https://www.cbc.ca/webfeed/rss/rss-topstories",
        "The Globe and Mail": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/",
        "BBC Latin America": "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
        "Mexico News Daily": "https://mexiconewsdaily.com/feed/",
        "MercoPress": "https://en.mercopress.com/rss",
        "Buenos Aires Times": "https://www.batimes.com.ar/feed",
        "BBC Mundo": "https://feeds.bbci.co.uk/mundo/rss.xml",
        "The Rio Times": "https://www.riotimesonline.com/feed/",
        "Global News Canada": "https://globalnews.ca/feed/",
        "National Post": "https://nationalpost.com/feed",
        "The Guardian US": "https://www.theguardian.com/us-news/rss",
    },
    "Technology": {
        "TechCrunch": "https://techcrunch.com/feed/",
        "The Verge": "https://www.theverge.com/rss/index.xml",
        "Wired": "https://www.wired.com/feed/rss",
        "Ars Technica": "https://feeds.arstechnica.com/arstechnica/index",
        "Hacker News": "https://news.ycombinator.com/rss",
        "MIT Technology Review": "https://www.technologyreview.com/feed/",
        "Engadget": "https://www.engadget.com/rss.xml",
        "BBC Technology": "https://feeds.bbci.co.uk/news/technology/rss.xml",
        "The Guardian Technology": "https://www.theguardian.com/technology/rss",
        "New York Times Technology": "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
        "ZDNet": "https://www.zdnet.com/news/rss.xml",
        "The Register": "https://www.theregister.com/headlines.atom",
        "Slashdot": "http://rss.slashdot.org/Slashdot/slashdotMain",
        "TechRadar": "https://www.techradar.com/rss",
        "CNET": "https://www.cnet.com/rss/news/",
        "IEEE Spectrum": "https://spectrum.ieee.org/feeds/feed.rss",
        "9to5Mac": "https://9to5mac.com/feed/",
        "Android Authority": "https://www.androidauthority.com/feed/",
        "Tom's Hardware": "https://www.tomshardware.com/feeds/all",
        "Techmeme": "https://www.techmeme.com/feed.xml",
        "Mashable": "https://mashable.com/feeds/rss/all",
        "Krebs on Security": "https://krebsonsecurity.com/feed/",
        "Bleeping Computer": "https://www.bleepingcomputer.com/feed/",
        "The Hacker News": "https://feeds.feedburner.com/TheHackersNews",
        "OpenAI News": "https://openai.com/news/rss.xml",
        "Google AI Blog": "https://blog.google/technology/ai/rss/",
        "Hugging Face Blog": "https://huggingface.co/blog/feed.xml",
    },
    "Science and Health": {
        "Nature": "https://www.nature.com/nature.rss",
        "Science Daily": "https://www.sciencedaily.com/rss/all.xml",
        "New Scientist": "https://www.newscientist.com/feed/home/",
        "Phys.org": "https://phys.org/rss-feed/",
        "Science News": "https://www.sciencenews.org/feed",
        "Quanta Magazine": "https://api.quantamagazine.org/feed/",
        "NASA Breaking News": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        "Scientific American": "http://rss.sciam.com/ScientificAmerican-Global",
        "BBC Science": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "The Guardian Science": "https://www.theguardian.com/science/rss",
        "New York Times Science": "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
        "Live Science": "https://www.livescience.com/feeds/all",
        "Science Magazine": "https://www.science.org/rss/news_current.xml",
        "STAT News": "https://www.statnews.com/feed/",
        "BBC Health": "https://feeds.bbci.co.uk/news/health/rss.xml",
        "New York Times Health": "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
        "The Lancet": "https://www.thelancet.com/rssfeed/lancet_current.xml",
        "Nature Medicine": "https://www.nature.com/nm.rss",
        "PLOS ONE": "https://journals.plos.org/plosone/feed/atom",
        "Science Alert": "https://www.sciencealert.com/feed",
        "Ars Technica Science": "https://feeds.arstechnica.com/arstechnica/science",
        "Eos": "https://eos.org/feed",
        "Mongabay": "https://news.mongabay.com/feed/",
        "Carbon Brief": "https://www.carbonbrief.org/feed/",
        "Yale Environment 360": "https://e360.yale.edu/feed.xml",
        "CDC Newsroom": "https://tools.cdc.gov/api/v2/resources/media/132608.rss",
        "ESA Space News": "https://www.esa.int/rssfeed/Our_Activities/Space_News",
    },
    "Business": {
        "BBC Business": "https://feeds.bbci.co.uk/news/business/rss.xml",
        "CNBC": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "Financial Times": "https://www.ft.com/rss/home",
        "The Economist": "https://www.economist.com/the-world-this-week/rss.xml",
        "Bloomberg Markets": "https://feeds.bloomberg.com/markets/news.rss",
        "MarketWatch": "http://feeds.marketwatch.com/marketwatch/topstories/",
        "Forbes": "https://www.forbes.com/business/feed/",
        "Fortune": "https://fortune.com/feed/",
        "Business Insider": "https://feeds.businessinsider.com/custom/all",
        "Yahoo Finance": "https://finance.yahoo.com/news/rssindex",
        "The Guardian Business": "https://www.theguardian.com/business/rss",
        "New York Times Business": "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
        "Harvard Business Review": "http://feeds.hbr.org/harvardbusiness",
        "CoinDesk": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "Cointelegraph": "https://cointelegraph.com/rss",
        "Seeking Alpha": "https://seekingalpha.com/feed.xml",
        "Entrepreneur": "https://www.entrepreneur.com/latest.rss",
        "Inc": "https://www.inc.com/rss",
        "Fast Company": "https://www.fastcompany.com/latest/rss",
        "Nasdaq": "https://www.nasdaq.com/feed/rssoutbound?category=Markets",
    },
    "Sport": {
        "BBC Sport": "https://feeds.bbci.co.uk/sport/rss.xml",
        "ESPN": "https://www.espn.com/espn/rss/news",
        "Sky Sports": "https://www.skysports.com/rss/12040",
        "The Guardian Sport": "https://www.theguardian.com/sport/rss",
        "BBC Football": "https://feeds.bbci.co.uk/sport/football/rss.xml",
        "CBS Sports": "https://www.cbssports.com/rss/headlines/",
        "Yahoo Sports": "https://sports.yahoo.com/rss/",
    },
}
ALL_NEWS_OUTLETS = {name: url for outlets in NEWS_OUTLETS.values() for name, url in outlets.items()}


# The publishers a literature survey can be restricted to, by the number (member) that Crossref gives to each of them.
# A search in a publisher only returns papers of that publisher (Springer Nature includes Nature, Springer and BMC for example).
# Every number below was checked with the Crossref API on 3 October 2026. The user can look for any other publisher by its name
# with findPublishers in harness_utils.py, which returns the number of the publishers Crossref knows.
PAPER_PUBLISHERS = {
    "Springer Nature": 297,
    "Elsevier": 78,
    "Wiley": 311,
    "IEEE": 263,
    "ACM": 320,
    "Taylor & Francis": 301,
    "SAGE": 179,
    "Oxford University Press": 286,
    "Cambridge University Press": 56,
    "MDPI": 1968,
    "Frontiers": 1965,
    "PLOS": 340,
    "Science (AAAS)": 221,
    "PNAS": 341,
    "eLife": 4374,
    "Cold Spring Harbor Laboratory (bioRxiv, medRxiv)": 246,
    "Association for Computational Linguistics": 1643,
    "AAAI": 9382,
    "MIT Press": 281,
    "IET": 265,
    "IOP Publishing": 266,
    "AIP Publishing": 317,
    "American Physical Society": 16,
    "American Chemical Society": 316,
    "Royal Society of Chemistry": 292,
    "Optica": 285,
    "Royal Society": 175,
    "American Mathematical Society": 14,
    "SIAM": 351,
    "De Gruyter": 374,
    "Emerald": 140,
    "IOS Press": 7437,
    "Copernicus": 3145,
    "BMJ": 239,
    "JAMA (American Medical Association)": 10,
    "New England Journal of Medicine (Massachusetts Medical Society)": 150,
    "Wolters Kluwer": 276,
    "JMIR Publications": 1010,
    "Annual Reviews": 22,
    "American Society for Microbiology": 235,
    "ASME": 33,
    "ASCE": 30,
    "University of Chicago Press": 200,
}

# The mail servers of the common providers: (SMTP server to send, IMAP server to read the replies, what the user must know).
# Emails are sent with STARTTLS on port 587 and read with SSL on port 993. Every server below accepted both connections on 4 October 2026
# (tests/live_checks.py servers tests them again).
EMAIL_PROVIDERS = {
    "Gmail": ("smtp.gmail.com", "imap.gmail.com", "Gmail does not accept your normal password here. Turn on 2-step verification, then create an app password at myaccount.google.com/apppasswords."),
    "Outlook / Hotmail / Microsoft 365": ("smtp-mail.outlook.com", "outlook.office365.com", "Some Microsoft accounts only accept an app password, or have SMTP login switched off by the administrator."),
    "Yahoo": ("smtp.mail.yahoo.com", "imap.mail.yahoo.com", "Yahoo needs an app password: create it in the security settings of your Yahoo account."),
    "iCloud": ("smtp.mail.me.com", "imap.mail.me.com", "iCloud needs an app-specific password, created at appleid.apple.com."),
    "Zoho": ("smtp.zoho.com", "imap.zoho.com", "Zoho may need an app password, and the servers are different for accounts outside the US (for example smtp.zoho.eu)."),
}

# The messaging apps a news briefing can be sent to. For each one: what the user is told (info), and the questions to ask (fields),
# in the same form as the fields of tasks_library.py. harness_utils.py has the code that sends to each one (MESSENGERS), under the same name.
# The tokens are only kept in memory while the program runs, and never saved. The API of each app was read on 4 October 2026.
MESSAGING_APPS = {
    "Telegram": {
        "info": "The briefing arrives as a message from a Telegram bot that you create yourself. It is free and takes about two minutes: in Telegram open the chat "
                "with @BotFather, send /newbot and follow the steps. It gives you the token of your bot. Then open your new bot, press Start and send it any message.",
        "fields": [
            {"key": "token", "ask": "Token of your Telegram bot (it looks like 123456789:ABCdef...)", "kind": "secret", "required": True,
             "help": "It is only kept in memory while the program runs, and never saved. Whoever has it can write as your bot."},
            {"key": "chat", "ask": "Your chat number (leave empty and I will find it for you)", "kind": "text", "default": "",
             "help": "It tells the bot where to write. Once you sent a message to your bot, I can find it myself."},
        ],
    },
    "WhatsApp": {
        "info": "The briefing arrives as a WhatsApp message from a WhatsApp Business app that you create for free at developers.facebook.com. You need a Meta developer "
                "account and a business portfolio, and the app gives you an access token and a phone number ID. The temporary token of the dashboard expires quickly, "
                "so create a permanent one with a system user (permissions whatsapp_business_messaging and whatsapp_business_management). "
                "IMPORTANT: WhatsApp only lets such an app write free text to someone who wrote to it in the last 24 hours. Send any message to the number of your app "
                "from your WhatsApp before the briefing is due, and again every day. If you did not, WhatsApp refuses the message and you are told so.",
        "fields": [
            {"key": "token", "ask": "Access token of your WhatsApp Business app", "kind": "secret", "required": True,
             "help": "It is only kept in memory while the program runs, and never saved. Whoever has it can write as your app."},
            {"key": "phoneId", "ask": "Phone number ID of your WhatsApp Business app", "kind": "text", "required": True,
             "help": "You find it in the WhatsApp section of your app in the Meta dashboard, next to the phone number. It is a long number, and it is not the phone number itself."},
            {"key": "to", "ask": "Your own WhatsApp number, with the country code (like +4915112345678)", "kind": "phone", "required": True},
        ],
    },
}
